# Generated by Django 5.1.7 on 2025-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donate_cpf_alter_donate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
